[package]
name = "nae"
version = "0.1.0"
authors = ["Nazariglez <nazari.nz@gmail.com>"]
edition = "2018"

#[lib]
#crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.3.0-alpha2"
wasm-bindgen = "0.2.51"

[dependencies.web-sys]
version = "0.3.28"
#package = "web_sys"
features = [
    "Document",
    "Window",
    "HtmlCanvasElement",
]

[features]